runtime: python37
entrypoint: daphne --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 backend.asgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto