version: '3.7'

services:
  gcloud:
    image: google/cloud-sdk:410.0.0
    volumes:
      - gcp-creds:/creds
      - .:/backend
    working_dir: /backend
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: